@TodoAPI_HostAddress = http://localhost:5262

### Todo API Requests
GET {{TodoAPI_HostAddress}}/todos
Accept: application/json


### Create a new Todo
POST {{TodoAPI_HostAddress}}/todos
Content-Type: application/json

{
    "title": "New Todo",
    "description": "This is a new todo item."
}

### Update an existing Todo
PATCH {{TodoAPI_HostAddress}}/todos/8
Content-Type: application/json

{

    "currentStatus": "InProgress"

}

### Test updating non-existent todo
PUT {{TodoAPI_HostAddress}}/todos/999
Content-Type: application/json

{
  "title": "This should fail",
  "currentStatus": "Completed"
}

### GET a specific Todo
GET {{TodoAPI_HostAddress}}/todos/2
Accept: application/json

### Delete a Todo
DELETE {{TodoAPI_HostAddress}}/todos/2

### search Todos
GET {{TodoAPI_HostAddress}}/todos?search=Ciao
Accept: application/json