@TodoAPI_HostAddress = http://localhost:5262

### Todo API Requests
GET {{TodoAPI_HostAddress}}/todos
Accept: application/json


### Create a new Todo
POST {{TodoAPI_HostAddress}}/todos
Content-Type: application/json

{
    "title": "New Todo"
}


